collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2626208
  brandStrength: 0.800812
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#231F20'
    - '#C8C7C7'
    - '#918F90'
  rhythmicContrast: 0.6439313
typography_spectrum: 0.434479
layout_spectrum: 0.3464017
name: serifsandsans
