layout_spectrum: 0.7000605
typography_spectrum: 0.9898688
color:
  saturation: 0.8966483
  lightness: 0.7784286
  brandStrength: 0.800812
  rhythmicContrast: 0.7011256
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: serifsandsans
